input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Yes)
    basic.pause(5000)
    Drones.Basic_action(Drones.Basicoptions.Takeoff)
    Drones.Hovering(2)
    Drones.Move_action(Drones.Directionoptions.Up, 100)
    Drones.Rotation_action(Drones.Angleoptions.Left, 90)
    Drones.Move_action(Drones.Directionoptions.Up, 100)
    music.play(music.stringPlayable("C5 G B A F A C5 B ", 120), music.PlaybackMode.UntilDone)
    Drones.Basic_action(Drones.Basicoptions.Landing)
})
Drones.initModule(Drones.Runmodes.Master)
